routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  //  return redirect()->route('login');
    return view('auth.login');
});


Auth::routes();

Route::middleware('auth')->group(function (){
  if (App::environment() == "remote"){
    Route::get('/dashboard',['uses' => 'ProductController@upload_product_view', 'as' => 'import_products']);
  }else{
    Route::get('/dashboard', 'ReportingController@index')->name('dash');
  }

  //Route::get('/dashboard', 'ProductController@index')->name('dash');

  //categories
  Route::get('/categories',['uses' => 'CategoryController@index','as' => 'categories']);
  Route::get('/new-category',['uses' => 'CategoryController@create','as' => 'newcategory']);
  Route::post('/save-category',['uses' => 'CategoryController@store','as' => 'savecategory']);
  Route::get('/edit-category/{cat_id}',['uses' => 'CategoryController@edit','as' => 'editcategory']);
  Route::post('/update-category/{cat_id}/category',['uses' => 'CategoryController@update','as' => 'updatecategory']);

   //prod
   Route::get('/products',['uses' => 'ProductController@index','as' => 'products']);
   Route::get('/new-product',['uses' => 'ProductController@create','as' => 'newproduct']);
   Route::post('/save-product',['uses' => 'ProductController@store','as' => 'saveproduct']);
   Route::get('/edit-product/{prod_id}',['uses' => 'ProductController@edit','as' => 'editproduct']);
   Route::post('/update-product/{prod_id}/product',['uses' => 'ProductController@update','as' => 'updateproduct']);
   Route::get('/import_products',['uses' => 'ProductController@upload_product_view', 'as' => 'import_products']);
   Route::get('/import_from_file',['uses' => 'ProductController@import_from_excel_product_view', 'as' => 'import_from_file']);
    Route::post('/process_products_pricelist',['uses' => 'ProductController@load_price_lists', 'as' => 'load_price_lists']);
    //rates
    Route::get('/exchange_rates',['uses' => 'ExchangeRateController@index','as' => 'exchangerates']);
    Route::get('/new-exchangerate',['uses' => 'ExchangeRateController@create','as' => 'newexchangerate']);
    Route::post('/save-exchangerate',['uses' => 'ExchangeRateController@store','as' => 'saveexchangerate']);
    Route::get('/edit-exchange/{id}',['uses' => 'ExchangeRateController@edit','as' => 'editexchangerate']);
    Route::post('/update-exchangerate/{id}',['uses' => 'ExchangeRateController@update','as' => 'updateexchangerate']);

     //shippmentplans
     Route::get('/shippingplans',['uses' => 'ShippingPlanController@index','as' => 'shippingplans']);
     Route::get('/new-plan',['uses' => 'ShippingPlanController@create','as' => 'newplan']);
     Route::post('/save-plan',['uses' => 'ShippingPlanController@store','as' => 'saveplan']);
     Route::get('/edit-plan/{plan_id}',['uses' => 'ShippingPlanController@edit','as' => 'editplan']);
     Route::post('/update-plan/{plan_id}',['uses' => 'ShippingPlanController@update','as' => 'updateplan']);

     //company
     Route::get('/company',['uses' => 'CompanyController@index','as' => 'company']);
     Route::post('/updatedemodata',['uses' => 'CompanyController@updateCompanyDemographics','as' => 'updatedemodata']); //updateCompanyLogo
     Route::post('/updatecompanylogo',['uses' => 'CompanyController@updateCompanyLogo','as' => 'updatecompanylogo']);
     Route::post('/updatePaynow',['uses' => 'CompanyController@updatePaynow','as' => 'updatePaynow']);

     Route::get('/transactions', ['uses' => 'TransactionController@showTransactions','as' => 'showTransactions']);
     Route::get('/attempts', ['uses' => 'TransactionController@showAttewmpts','as' => 'showAttewmpts']);
     Route::get('/customers', ['uses' => 'TransactionController@Customers','as' => 'Customers']);
     Route::get('/update_invoice/{inv_number}', ['uses' => 'TransactionController@viewUpdateInvoiceStatus','as' => 'viewUpdateInvoiceStatus']);
     Route::post('/updateinvoice', ['uses' => 'TransactionController@processInvoiceStatus','as' => 'processInvoiceStatus']);
     Route::resource('user', 'UserController');
     Route::get('/transaction/{ref}', ['uses' => 'TransactionController@TransactionDetails','as' => 'TransactionDetails']);
     Route::get('/push-to-sap', ['uses' => 'TransactionController@invoicesToPush','as' => 'pushToSap']);
     //Route::get('/sms_balance', ['uses' => 'TransactionController@ShowBalance','as' => 'getSMSBalance']);

     //sap integrations
    // Route::get('/cart_materials', ['uses' => 'SapIntegrationController@show_materials']);
     Route::post('/materials_upload', ['uses' => 'SapIntegrationController@get_all_materials_with_details', 'as' =>  'materials_upload']);
     Route::get('/UploadPrices', ['uses' => 'SapIntegrationController@cart_price_list']);
     Route::get('/sync_invoices',['uses' => 'SapInvoicingController@syncInvoicesToSap', 'as' => 'sync_invoices']);
     Route::get('/webservices_configs',['uses' => 'SAPWebServicesController@index', 'as' => 'sapweb']);
     Route::get('/pick_up_points',['uses' => 'SAPWebServicesController@newpickup', 'as' => 'newpickup']);
     Route::post('/updatewebservice',['uses' => 'SAPWebServicesController@saveWebServiceSettings','as' => 'updatewebservice']);
     Route::post('/createpickups',['uses' => 'SAPWebServicesController@savePickUpPointsSettings','as' => 'createpickups']);
     Route::post('/updatepickups/{id}',['uses' => 'SAPWebServicesController@updatePickUpPointsSettings','as' => 'updatepickups']);
     Route::get('/editpoint/{id}',['uses' => 'SAPWebServicesController@edit','as' => 'editpoint']);
     Route::get('/storage_locations',['uses' => 'SAPWebServicesController@vwStorageLocations', 'as' => 'vwStorageLocations']);
     Route::get('/sloc_products/{sloc}',['uses' => 'SAPWebServicesController@vwStorageLocProducts', 'as' => 'vwStorageLocProducts']);
     Route::get('/upload_sap_register',['uses' => 'SapInvoicingController@import_from_excel_invoice_view', 'as' => 'upload_sap_register']);
     Route::post('/process_sap_register',['uses' => 'SapInvoicingController@load_billing_documents', 'as' => 'process_sap_register']);
     //editpoint

   //  Route::get('/sales_offices_pricing', ['uses' => 'SapIntegrationController@sales_office_price_list']);
   
   //exceptions
   Route::get('exceptions/receipts',['uses' => 'ExceptionsController@ListFailedTransactions', 'as' => 'failed_trans']);
   Route::get('exceptions/receipts/{order_ref}',['uses' => 'ExceptionsController@FixFailedTrans', 'as' => 'fix_trans']);

   //reports
   Route::get('/usersList', 'ReportingController@index')->name('usersList');


});

Route::middleware('auth')->get('logout', function() {
    Auth::logout();
    return redirect(route('login'))->withInfo('You have successfully logged out!');
})->name('logout');

Route::get('site/shutdown', function(){
  return Artisan::call('down');
});

Route::get('site/live', function(){
  return Artisan::call('up');
}); 

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable , HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    //protected $connection = 'mysql2';
    
    protected $fillable = [
        'name', 'email', 'password', 'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Contracts\Role;
use Spatie\Permission\Models\Role as ModelsRole;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('users.index')->with(compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = ModelsRole::all();
        return view('users.create')->with(compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'min:6|required',
            'cpassword' => 'same:password'
        ],[
            'password.length' => 'Password must be at least six characters.',
           // 'password.regex' => 'Password must have different characters.'
        ]);
        $input = $request->all();
            $input['password'] = Hash::make($request->input('password'));
            $user = User::create($input);
            $user->assignRole($request->input('role'));

            return redirect()->route('user.index')->with('message','User has been created succesfully..');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/create.blade.php
 
        @extends('layouts.app')
        <!-- wrap @s -->
        @section('content')

        <div class="nk-content ">
            <div class="container-fluid">
                <div class="nk-content-inner">
                    <div class="nk-content-body">
                        <div class="components-preview wide-md mx-auto">
                           
                            <div class="nk-block nk-block-lg">
                                <div class="nk-block-head">
                                    <div class="nk-block-head-content">
                                        <h4 class="title nk-block-title">New User</h4> 
                                        <div class="nk-block-des">
                                            {{-- <p class="alert alert-fill alert-info alert-icon"> <strong> {{ config('app.BASE_CURRENCY') }} Paired Currency combinations </strong> : {{ $currencies }}</p> --}}
                                            @if (session('message'))
                                            <br>
                                            <p class="alert alert-fill alert-success alert-icon">{{ session('message') }}</p>
                                       @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="card card-bordered card-preview">
                                    <div class="card-inner">
                                        <div class="preview-block">
                                            {{-- <span class="preview-title-lg overline-title">Default Preview</span> --}}
                                        <form action="{{route('user.store')}}" method="POST" enctype="multipart/form-data">
                                          @csrf
                                            <div class="row gy-4">
                                                <div class="col-sm-8">
                                                    <div class="form-group">
                                                        <label class="form-label" for="default-01">Name</label>
                                                        <div class="form-control-wrap">
                                                        <input type="text" name="name" class="form-control form-control-lg @error('name') is-invalid @enderror" value="{{old('name')}}" id="currency_code" placeholder="Enter  Name " required>
                                                            @error('name')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                        @enderror
                                                        </div>
                                                    </div>
                                                </div>

                                                

                                                <div class="col-sm-8">
                                                    <div class="form-group">
                                                        <label class="form-label" for="default-05">Email Address</label>
                                                        <div class="form-control-wrap">
                                                            <div class="form-text-hint">
                                                                <span class="overline-title">user@user.com</span>
                                                            </div>
                                                        <input type="email" name="email" class="form-control  form-control-lg @error('email') is-invalid @enderror" value="{{old('email')}}" id="default-05" placeholder="Enter user email">
                                                            @error('email')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                        @enderror
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-sm-8">
                                                    <div class="form-group">
                                                        <label class="form-label">User Role</label>
                                                        <div class="form-control-wrap">
                                                            <select class="form-select form-control-lg @error('role') is-invalid @enderror" name="role" data-ui="lg" data-search="on" required>
                                                               @foreach ($roles as $role)
                                                            <option value="{{$role->id}}">{{$role->name}}</option>
                                                               @endforeach
                                                            </select>

                                                            @error('role')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                        @enderror
                                                        </div>
                                                    </div>
                                                </div>

                                                
                                                <div class="col-sm-6">
                                                    <div class="form-group">
                                                        <label class="form-label" for="default-05">User Password</P></label>
                                                        <div class="form-control-wrap">
                                                            <div class="form-text-hint">
                                                                <span class="overline-title">Secure Key</span>
                                                            </div>
                                                        <input type="password" name="password" class="form-control  form-control-lg @error('password') is-invalid @enderror" value="{{old('password')}}" id="default-05" placeholder="Enter User Default Password">
                                                            @error('password')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                        @enderror
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-sm-6">
                                                    <div class="form-group">
                                                        <label class="form-label" for="default-05">Confirm Password</P></label>
                                                        <div class="form-control-wrap">
                                                            <div class="form-text-hint">
                                                                <span class="overline-title">Secure Key</span>
                                                            </div>
                                                        <input type="password" name="cpassword" class="form-control  form-control-lg @error('cpassword') is-invalid @enderror" value="{{old('cpassword')}}" id="default-05" placeholder="Re Enter password to confirm">
                                                            @error('cpassword')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                        @enderror
                                                        </div>
                                                    </div>
                                                </div>

                                              

                                            <div class="col-sm-8">
                                                    <div class="form-group">
                                                        <button type="submit" class="btn btn-lg btn-primary">Save User</button>
                                                    </div>
                                                
                                                </div>
                                                
                                                </div>

                                                
                                                
                                            </div>
                                        </form>
                                            
                                        </div>
                                    </div>
                                </div><!-- .card-preview -->
                                
                            </div><!-- .nk-block -->
                           
                            
                            
                        </div><!-- .components-preview -->
                    </div>
                </div>
            </div>
        </div>

        @endsection

        @section('js')

        <script>
            $(document).ready(function () {
    
    
            })
        </script>
        @endsection